### ISSUE TITLE
Introduce Dynaconf

### ISSUE THREAD

**Issue by Volscente** [Volscente/MediBioticsAI#30]
# Description
As a Data Scientist,

I want to introduce the usage of Dynaconf as new settings & configuration management,

In order to better organise the settings of the project and the division between different environments.

# Changelog
- [x] Add Configuration `test_config.toml` in `configuration`
- [x] Refactor PyTest `conftest.py` with Dynaconf in `tests`
- [x] Remove Configuration `test_config.yaml` in `configuration`
- [ ] Refactor PyTest `test_general_utils.py` in `tests`

**Comment by Volscente** [comment]
# Example
```python
settings_path = "../mds/config/settings.toml"
settings = Dynaconf(settings_files=[settings_path], environments=True, env="DEV")
```

```toml
[default]
model_name = "gpt-4-turbo"
split_large_image = true
seed = 1234
flow = "ocr_gemini"
```
